//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP.LSP.Tools.DiskMon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DP.LSP.Tools.DiskMon.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string DriveAllKey {
            get {
                return ResourceManager.GetString("DriveAllKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--%LOW DRIVES%--&gt;.
        /// </summary>
        internal static string EmailLowDrivesPlaceholderKey {
            get {
                return ResourceManager.GetString("EmailLowDrivesPlaceholderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--%SERVER%--&gt;.
        /// </summary>
        internal static string EmailMachinePlaceholderKey {
            get {
                return ResourceManager.GetString("EmailMachinePlaceholderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--%OTHER DRIVES%--&gt;.
        /// </summary>
        internal static string EmailOtherDrivesPlaceholderKey {
            get {
                return ResourceManager.GetString("EmailOtherDrivesPlaceholderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastReportDate.
        /// </summary>
        internal static string LastReportDateKey {
            get {
                return ResourceManager.GetString("LastReportDateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailSender.
        /// </summary>
        internal static string MailSenderKey {
            get {
                return ResourceManager.GetString("MailSenderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailSubject.
        /// </summary>
        internal static string MailSubjectKey {
            get {
                return ResourceManager.GetString("MailSubjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportingFrequency.
        /// </summary>
        internal static string ReportingFrequencyKey {
            get {
                return ResourceManager.GetString("ReportingFrequencyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmtpHost.
        /// </summary>
        internal static string SmtpHostKey {
            get {
                return ResourceManager.GetString("SmtpHostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmtpPort.
        /// </summary>
        internal static string SmtpPortKey {
            get {
                return ResourceManager.GetString("SmtpPortKey", resourceCulture);
            }
        }
    }
}
